// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjuxjykzmpnbsnifmfjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqdXhqeWt6bXBuYnNuaWZtZmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODkwNTksImV4cCI6MjA3MTc2NTA1OX0.3VQC_cLjKX7HyGjGYom9IC5bWP061eFrmFB4p9EaDuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});